name: Download Lenovo File

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download file
        run: |
          wget \
          -O "firmware.zip" \
          "https://rsddownload-secure.lenovo.com/ROADSTR_G_W1WRS36.39-73-3-1_subsidy-DEFAULT_regulatory-DEFAULT_cid50_CFC.xml.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: firmware.zip
